### ISSUE TITLE
World Map doesn't get generated properly

### ISSUE THREAD

**Issue by d3v0ps** [d3v0ps/metaverse#44]
**Describe the bug**
The World Map doesn't generate the burgs described in the data json

**To Reproduce**
1. Open the World Map
2. Search a Burg from the World Map in the Burg Selector
3. Burg isn't on the list

**Expected behavior**
Burgs should match the map ones

**Comment by IvanToy** [comment]
Hi. I would like to work on this. I have a question. I looked at the 001.json file and as I understand it is the file that is used to generate the map. In this file, I didn't find any burgs that are placed on the map. Could you please tell me where do the burgs on the map come from? For example, I could not find this:
<img width="318" alt="Screen Shot 2022-05-01 at 12 31 45 AM" src="https://user-images.githubusercontent.com/68671067/166132321-0f9efb6b-37d2-43ce-b0f9-705d31035314.png">
Thank you

**Comment by d3v0ps** [comment]
Hi @IvanToy Thank you for getting interested in the project! The world map is a web app itself (see [Azgaar's Fantasy Map Generator)](https://github.com/Azgaar/Fantasy-Map-Generator). What I did was to export the data (the 001.json is a superset of it) from a randomly generated map and created a [fork here](https://github.com/d3v0ps/Fantasy-Map-Generator) to be able to set properties by URL (like the seed id). Theoretically the seed Id should suffice but it doesn't seem to work correctly.

**Comment by IvanToy** [comment]
@d3v0ps Does it mean that burgs in the 001.json file should be rendered on the map as well?
Because as far as I can tell,  burgs that are in 001.json file are rendered in burg-selector.component.ts.

**Comment by d3v0ps** [comment]
@IvanToy no, burgs should be rendered in the map just based on the 001.json map seedId (see world-map.component). The data in the 001.json is there just to be used around the app, but we are only sending the seed Id to the map

**Comment by d3v0ps** [comment]
See [Allow loading map from url parameters](https://github.com/Azgaar/Fantasy-Map-Generator/pull/788), and [The file does not look like a valid .map file. Please check the data format with v1.8 map ](https://github.com/Azgaar/Fantasy-Map-Generator/issues/790#issuecomment-1115154428)

**Comment by d3v0ps** [comment]
Fixed at 82f962f8a92a8aca9c37e4df6d98040aca104ca2
